version: '2'

services:
  db:
    image: mhhoban/dukedoms-rdbs
    environment:
      POSTGRES_PASSWORD: daleria
    ports:
      - 5432:5432
  mock-card-service:
    image: mhhoban/dukedoms-mock-card-service
    ports:
      - 5005:8080
